### ISSUE TITLE
Bash's $Random is a weak entropy source

### ISSUE THREAD

**Issue by madblobfish** [cryptolok/GhostInTheNet#6]
In [line 96](https://github.com/cryptolok/GhostInTheNet/blob/1015db9a6c5ce06d7b594927b0a67b8f1afdba4c/GhostInTheNet.sh#L96) you use Bash's $RANDOM for the generation of a random mac address. $RANDOM returns an integer between 0 and 32767 (see RANDOM on the [manpage](https://linux.die.net/man/1/bash)). So the generated mac address has only about 2 bytes entropy.
A mac address has [8 bytes](https://en.wikipedia.org/wiki/MAC_address), as you hardcode the first byte you would need 7bytes of entropy for an perfectly random address.

I have no idea of the impact and if it is possible that a scanner could detect usage of this script through the 32768 different mac addresses that all start with 64.

So please use another way to generate a random mac address. How about one of the following:
```
dd if=/dev/urandom bs=8 count=1 2>/dev/null | od -t x8 | sed -nE 's/0000000 (..)(..)(..)(..)(..)(..)(..)..$/64:\1:\2:\3:\4:\5/p'
cat /proc/sys/kernel/random/uuid
```
It could also be possible to make networkmanager generate the mac address see: https://blogs.gnome.org/thaller/2016/08/26/mac-address-spoofing-in-networkmanager-1-4-0/

**Comment by cryptolok** [comment]
First of all, MAC address is constisted out of 6 bytes and not 8, as you can see by the same [link](https://en.wikipedia.org/wiki/MAC_address) you mentioned, since 48 bits is 6 bytes (as 48/8=6) :)
Second of all, the hardcoded byte (so 5 bytes of entropy left) was a "trick" in order not to use [reserved](https://tools.ietf.org/html/rfc5342) MAC addresses that won't work in a network environment.
Now, the BASH's $RANDOM output is log(32768,2)=15 bits of entropy, or less then 2 bytes, which is not enough of course, but since I use MD5 hash in order to extend the result, it would form the MAC address of the necessery length.
I do agree, however, that potentially a network filtering equipment can make a list of all possible addresses of my script and then just blacklist those MACs, regardless a pretty low probability of such implementation.
As you might red from comments on [line 98](https://github.com/cryptolok/GhostInTheNet/blob/1015db9a6c5ce06d7b594927b0a67b8f1afdba4c/GhostInTheNet.sh#L98), a better solution is to have a list of vendors (Dell, HP, Apple, etc) for the first EUI 3 bytes, and then just put 3 random bytes, thus eliminating possibility of blacklisting. That what I will do regarding your notes, but for now, I will only implement HP vendor since, it's one of the largest, thus difficult to blacklist.
I do aware of network manager (and other system) tricks (nice article by the way), but sometime you can have MAC filtering and will have to make exceptions for those networks, not even speacking that not everyone uses NM, while I seek universality with my script, this is why I prefered to use a concept of not hiding the identity only if needed so, which is the philosophy for the most users, even if I understand that it's better to implement a default system policy.
Thanks for useful information and contribution :)

**Comment by madblobfish** [comment]
No problem :) I'm happy to contribute.

Sorry about my 6 vs 8 byte slipup. I proposed using networkmanager as nmcli is already used in the script, which is from networkmanager as far as I know.

Your solution of using a list of vendors is probably the best way to go. A list of mac address prefix assignments can be found on the right side under "Download Public Listing" here: https://standards.ieee.org/develop/regauth/
