### ISSUE TITLE
@parrotOS renamed to @@4413

### ISSUE THREAD

**Issue by DoxingMethod** [cryptolok/GhostInTheNet#7]
For some reason, once using this once, my Tor won't open anymore and my @parrotOS in MATE Terminal has been changed to @@4413. Anyway to fix this?

**Comment by cryptolok** [comment]
4413 is the random hostname, which was assigned for privacy purpose (regarding DHCP), so it's normal
what isn't normal however, is that it stays persistent after reboot, which is due to my recent code update :) but I just commited a patch for it and changed the instructions a little bit, so it should be OK from here
I also tested Tor bundle on a live ParrotOS and it worked as well, just like AnonSurf, of course you shold use Ghost first and only then Tor
can you confirm that it's working properly now?

**Comment by DoxingMethod** [comment]
It seems to be working <3
Thanks man.

**Comment by cryptolok** [comment]
thnk you for contribution :)
